services:
  pdf-to-csv:
    build: .
    container_name: pdf-to-csv-webapp
    restart: unless-stopped
    ports:
      - "8090:8000"
    volumes:
      - ./jobs:/app/jobs
    networks:
    networks:
      - arr_network

networks:
  arr_network:
    external: true
